#!/usr/bin/python3

import os;
import shutil;
import sys;

for target in sys.argv[1:]:
    relpath = os.path.relpath(target, os.getenv("HOME"));
    linkfrom = os.path.join("{cwd}", relpath);
    if not os.path.exists(os.path.dirname(linkfrom)):
        os.makedirs(os.path.dirname(linkfrom));
    shutil.move(target,linkfrom);
    os.symlink(linkfrom,target);
    
